In [106]:
# Saka Raheem
# CSCI 5015
# Assignment #4
# March 27, 2025
# Exercise#1 : Defining One- dimensional and two-dimensional array.

In [107]:
# Here we are importanting the numpy into our code
import  numpy as np
# Here we are defining our array name my_array1
my_array1 = np.array([1, 2, 3, 4, 5, 6, 7,8])
print(f" One-dimensional array is : {my_array1}")


 One-dimensional array is : [1 2 3 4 5 6 7 8]


In [108]:
# Here we are defining our array name my_array2
my_array2 = np.array([[1, 2, 3, 4],
                       [4, 5, 6, 7]])
print(f" Two-dimensional array is : \n{my_array2}")

 Two-dimensional array is : 
[[1 2 3 4]
 [4 5 6 7]]


In [109]:
# Saka Raheem
# CSCI 5015
# Assignment #4
# March 27, 2025
# Exercise#2 : Appending a number to my_array1 [1, 2, 3, 4, 5, 6, 7,8]

In [110]:
import  numpy as np
my_array1 = np.array([1, 2, 3, 4, 5, 6, 7,8])

# Here we are defining the number tht need to be append into our existing my_array1
my_appendable_number = 9

# Here we are appending using the np.append() method
my_appendable_array = np.append(my_array1, my_appendable_number) 

# Here we are printing the new array with the append number " 9"
print(f" array({my_appendable_array})")


 array([1 2 3 4 5 6 7 8 9])


In [111]:
# Saka Raheem
# CSCI 5015
# Assignment #4
# March 27, 2025
# Exercise#3: Double the elements in One -dimensional array name " my_array1"

In [112]:
# Here we are importanting the numpy into our code
import  numpy as np

# Here we are defining our array name my_array1
my_double_array = 2*my_array1

# Here we are printing the doubling of our One-dimensional array name " my_double_array
print(f" 2*my_array : {my_double_array}")

 2*my_array : [ 2  4  6  8 10 12 14 16]


In [113]:
# Saka Raheem
# CSCI 5015
# Assignment #4
# March 27, 2025
# Exercise#4: The square root of an array anme my_array1. The output should be

In [114]:
# Here we are importanting the numpy into our code
import  numpy as np

# Here we are defining our array name my_array1
my_array1 = np.array([1, 2, 3, 4, 5, 6, 7,8])

# Here we are defining the varibale for square root 
my_array_sqrt = np.sqrt(my_array1)

# Here we are printing the doubling of our One-dimensional array name " my_double_array
print(f" The square root of my_array is : {my_array_sqrt}")

 The square root of my_array is : [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712]


In [115]:
# Saka Raheem
# CSCI 5015
# Assignment #4
# March 27, 2025
# Exercise#5: Confirm that my_array1 is one dimension, and my_array2 is two dimensions

In [116]:
# Method #1 using the ndim method
# Here we are importanting the numpy into our code
import  numpy as np

# Here we are defining our array name my_array1
my_array1 = np.array([1, 2, 3, 4, 5, 6, 7,8])

# Here we are defining our array name my_array2
my_array2 = np.array([[1, 2, 3, 4],
                       [4, 5, 6, 7]])

# Here we are checking the dimension of my_array1 and my_array2
print(f"my_array1 dimensions: {my_array1.ndim}")
print(f"my_array2 dimensions: {my_array2.ndim}")

# We can simple confimr by using
#print("my_array1 dimensions:", my_array1.ndim)
#print("my_array2 dimensions:", my_array2.ndim)

my_array1 dimensions: 1
my_array2 dimensions: 2


In [117]:
# Method #2 using the shape method
# Here we are importanting the numpy into our code
import  numpy as np

# Here we are defining our array name my_array1
my_array1 = np.array([1, 2, 3, 4, 5, 6, 7,8])

# Here we are defining our array name my_array2
my_array2 = np.array([[1, 2, 3, 4],
                       [4, 5, 6, 7]])


# Here we are printing to confirm the the dimension of both array name "my_array1" and "my_array2"
print(f"Number of dimensions (my_array1): {len(my_array1.shape)}")
print(f"Number of dimensions (my_array2): {len(my_array2.shape)}")

# We can simple confimr by using
#print("Number of dimensions (my_array1):", len(my_array1.shape))
#print("Number of dimensions (my_array2):", len(my_array2.shape))

Number of dimensions (my_array1): 1
Number of dimensions (my_array2): 2


In [118]:
# Saka Raheem
# CSCI 5015
# Assignment #4
# March 27, 2025
# Exercise#6: Confirming that my_array2 has two rows and three columns.

In [119]:
# Here we are importanting the numpy into our code
import  numpy as np
# Here we are defining our array name my_array2
my_array2 = np.array([[1, 2, 3, 4],
                       [4, 5, 6, 7]])

# Here wer are defing the rows_columns variable for our new array
rows_columns = my_array2.shape

# here we are print the number of rows and columns in the array name "my_array2"
print(rows_columns )

(2, 4)


In [120]:
# Saka Raheem
# CSCI 5015
# Assignment #4
# March 27, 2025
# Exercise#7: Printing the minimum and maximum elements for my_array1 and my_array2

In [121]:
# Here we are importanting the numpy into our code
import  numpy as np

# Here we are defining our array name my_array1
my_array1 = np.array([1, 2, 3, 4, 5, 6, 7,8])

# Here we are defining our array name my_array2
my_array2 = np.array([[1, 2, 3, 4],
                       [4, 5, 6, 7]])

# Here we are printing the mininmum and maximum element for my_array1 and my_array
print( f"Minimum value for my_array1 is :  {my_array1.min()}")
print( f"Minimum value for my_array1 is :  {my_array1.max()}")
print( f"Minimum value for my_array1 is :  {my_array2.min()}")
print( f"Minimum value for my_array1 is :  {my_array2.max()}")

# Here we can
#print( "Minimum value for my_array1 is :" , my_array1.min())
#print( "Minimum value for my_array1 is :" , my_array1.max())
#print( "Minimum value for my_array1 is :" , my_array2.min())
#print( "Minimum value for my_array1 is :" , my_array2.max())

Minimum value for my_array1 is :  1
Minimum value for my_array1 is :  8
Minimum value for my_array1 is :  1
Minimum value for my_array1 is :  7


In [122]:
# Saka Raheem
# CSCI 5015
# Assignment #4
# March 27, 2025
# Exercise#8 : Calculating the mean and standard deviation for my_array1 and my_array2.

In [123]:
# Here we are importanting the numpy into our code
import  numpy as np
# Here we are defining our array name my_array1
my_array1 = np.array([1, 2, 3, 4, 5, 6, 7,8])

# Here we are defining our array name my_array2
my_array2 = np.array([[1, 2, 3, 4],
                       [4, 5, 6, 7]])

# Here we are using the f-string to print the min and max of our array.
print( f"mean of my_array1 =  {my_array1.min()}")
print( f"std of my_array1 =  {my_array1.max()}")
print( f"mean of my_array2 =   {my_array2.std()}")
print( f"std of my_array2 =  {my_array2.std()}")

# Here we are using simply string to print out the mean and standard deviation of my_array1 and my_array2
#print( "mean of my_array1 = " , my_array1.mean())
#print( "std of my_array1 = " , my_array1.max())
#print( "mean of my_array2 = :" , my_array2.std())
#print( "std of my_array2 = " , my_array2.std())


mean of my_array1 =  1
std of my_array1 =  8
mean of my_array2 =   1.8708286933869707
std of my_array2 =  1.8708286933869707


In [100]:
print("It was nice learning about Array or NumPy array: collection of elements of the same data type, stored in a contiguous memory location memory location. With advantage allowing mathematical operations and data manipulation to be performed quickly.")

It was nice learning about Array or NumPy array: collection of elements of the same data type, stored in a contiguous memory location memory location. With advantage allowing mathematical operations and data manipulation to be performed quickly.
